services:

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: profscore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '15432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - internal_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
